common_vars:
  # Classic DTAP
  allowed_envs: &allowed_envs
    - dev
    - sit
  allowed_regions: &allowed_regions
    - eu-west-1
  main_region: &main_region
    - eu-west-1

common_tags: &common_tags
  Organization: "BPI"
  Terraform: "true"
  InfraRepo: "https://github.com/vmulasmob/blueprint-dtap"
  ManagedBy: "bpi-devops@mobiquityinc.com"


terragrunt_modules_settings:

  global:
    route53:
      dev.kibaws.mobiquitylab.tech:
        allowed_regions: *main_region
        allowed_envs:
          - dev
        repo: "git@github.com:vmulasmob/terraform_modules.git//route53/zones?ref=v0.3"

      dev_public:
        allowed_envs:
          - dev
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//route53/zone?ref=v0.3"

      dev_private:
        allowed_envs:
          - dev
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//route53/zone?ref=v0.3"

      sit.kibaws.mobiquitylab.tech:
        allowed_envs:
          - sit
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//route53/zones?ref=v0.3"

      sit_private:
        allowed_envs:
          - sit
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//route53/zone?ref=v0.3"

      sit_public:
        allowed_envs:
          - sit
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//route53/zone?ref=v0.3"

    iam:
      RoleAWSAlb:
        allowed_envs: *allowed_envs
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//iam?ref=v0.3"
        tf_variables:
          assume_role: "ec2.amazonaws.com"
          name: "RoleAWSAlb"
          policy_assume_role_file: "policy-assume-role-RoleAWSAlb.json"
          policy_file: "policy-RoleAWSAlb.json"

      RoleEKSControl:
        allowed_envs: *allowed_envs
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//iam?ref=v0.3"
        tf_variables:
          assume_role: "eks.amazonaws.com"
          managed_policy:
            - "arn:aws:iam::aws:policy/AmazonEKSClusterPolicy"
          name: "RoleEKSControl"
          policy_assume_role_file: "policy-assume-role-generic.json"

      RoleEksWorker:
        allowed_envs: *allowed_envs
        allowed_regions: *main_region
        repo: "git@github.com:vmulasmob/terraform_modules.git//iam?ref=v0.3"
        tf_variables:
          assume_role: "ec2.amazonaws.com"
          managed_policy:
            - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly"
            - "arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy"
            - "arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy"
            - "arn:aws:iam::aws:policy/AWSCertificateManagerReadOnly"
          name: "RoleEksWorker"
          policy_assume_role_file: "policy-assume-role-generic.json"

      RoleDataLifecycleManager:
        allowed_envs: 
          - dev
        allowed_regions: *main_region
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//iam?ref=v0.3"
        tf_variables:
          assume_role: "dlm.amazonaws.com"
          managed_policy:
            - "arn:aws:iam::aws:policy/service-role/AWSDataLifecycleManagerServiceRole"
          name: "RoleDataLifecycleManager"
          policy_assume_role_file: "policy-assume-role-generic.json"

      RoleEC2MicrosoftAD:
        allowed_envs:
          - sit
        allowed_regions: *main_region
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//iam?ref=v0.3"
        tf_variables:
          assume_role: "ec2.amazonaws.com"
          managed_policy:
            - "arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore"
            - "arn:aws:iam::aws:policy/AmazonSSMDirectoryServiceAccess"
          name: "RoleEC2MicrosoftAD"
          policy_assume_role_file: "policy-assume-role-generic.json"

      RoleMatomoDB:
        allowed_envs:
          - dev
        allowed_regions: *main_region
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//iam?ref=v1.5.0"
        tf_variables:
          assume_role: "ec2.amazonaws.com"
          policy_file: "policy-RoleMatomo.json"
          name: "RoleMatomo"
          policy_assume_role_file: "policy-assume-role-generic.json"
        
      RoleMatomoApp:
        allowed_envs:
          - dev
        allowed_regions: *main_region
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//iam?ref=v1.5.0"
        tf_variables:
          assume_role: "ec2.amazonaws.com"
          name: "RoleMatomoApp"
          policy_assume_role_file: "policy-assume-role-RoleJenkinsbackup.json"

  regional:
    vpc_eks_1:
      networking:
        allowed_envs: *allowed_envs
        allowed_regions: *allowed_regions
        repo: "git::https://github.com/terraform-aws-modules/terraform-aws-vpc.git//?ref=v2.24.0"
        tf_variables:
          default_vpc_name: "vpc_eks"
          enable_dns_hostnames: true
          enable_ipv6: false
          enable_nat_gateway: false
          single_nat_gateway: false
          tags:
            <<: *common_tags

      route_vpc_to_vpc:
        allowed_envs: *allowed_envs
        allowed_regions: *allowed_regions
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//route_vpc_to_vpc?ref=v0.3"

      transit_gateway_attachment:
        allowed_envs: *allowed_envs
        allowed_regions: *allowed_regions
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//transit_gateway_attachment?ref=v0.3"

    vpc_eks_2:
      networking:
        allowed_envs: *allowed_envs
        allowed_regions: *allowed_regions
        repo: "git::https://github.com/terraform-aws-modules/terraform-aws-vpc.git//?ref=v2.24.0"
        tf_variables:
          default_vpc_name: "vpc_eks"
          enable_dns_hostnames: true
          enable_ipv6: false
          enable_nat_gateway: false
          single_nat_gateway: false
          tags:
            <<: *common_tags

      route_vpc_to_vpc:
        allowed_envs: *allowed_envs
        allowed_regions: *allowed_regions
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//route_vpc_to_vpc?ref=v0.3"

      transit_gateway_attachment:
        allowed_envs: *allowed_envs
        allowed_regions: *allowed_regions
        repo: "git::https://github.com/vmulasmob/terraform_modules.git//transit_gateway_attachment?ref=v0.3"
